name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: dotnet restore Sitecore.Commerce.Plugin.Categories/Sitecore.Commerce.Plugin.Categories.csproj
    - name: Build
      run: dotnet build --configuration Release --no-restore Sitecore.Commerce.Plugin.Categories/Sitecore.Commerce.Plugin.Categories.csproj
